Repository googleapis/nodejs-functions, pull requests merged in 2020-08, with the labels that each got.

#6 fix: run synthtool hack to compile code
  README.md
  __pycache__/synth.cpython-37.pyc
  linkinator.config.json
  synth.metadata
  synth.py
Labels: cla: yes

#10 chore: update protos
  linkinator.config.json
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#14 build: use gapic-generator-typescript v1.0.7, use protos
  src/v1/cloud_functions_service_client.ts
  synth.metadata
Labels: automerge, cla: yes, context: partial

#16 build: fix wrong link in repo-metadata, ran synthtool
  .kokoro/populate-secrets.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  .repo-metadata.json
  README.md
  __pycache__/synth.cpython-37.pyc
  linkinator.config.json
  protos/protos.d.ts
  protos/protos.js
  samples/README.md
  synth.metadata
Labels: cla: yes

#11 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: partial

#17 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#18 build: move system and samples test from Node 10 to Node 12
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  synth.metadata
Labels: api: cloudfunctions, cla: yes, context: full

#20 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
