Repository googleapis/nodejs-functions, pull requests merged in 2020-09, with the labels that each got.

#22 feat: promote library to GA
  .repo-metadata.json
  README.md
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: api: cloudfunctions, cla: yes

#25 chore: update proto imports
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#27 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full
