Repository googleapis/nodejs-functions, pull requests merged in 2020-11, with the labels that each got.

#36 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#38 fix: do not modify options object, use defaultScopes
  __pycache__/synth.cpython-37.pyc
  package.json
  src/index.ts
  src/v1/cloud_functions_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: cloudfunctions, automerge, cla: yes

#41 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/cloud_functions_service_client.ts
  synth.metadata
Labels: api: cloudfunctions, cla: yes, context: none

#43 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full
