Repository googleapis/nodejs-functions, pull requests merged in 2021-02, with the labels that each got.

#52 chore: update CODEOWNERS config
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: cloudfunctions, automerge, cla: yes

#51 build: migrate to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
Labels: api: cloudfunctions, automerge, cla: yes

#48 chore: add ResourceDescriptor style to protos
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: cloudfunctions, cla: yes, context: none

#54 chore: update CODEOWNERS and bot config
  .github/CODEOWNERS
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: cloudfunctions, cla: yes, context: partial

#55 docs: update sample, regenerate README
  README.md
  samples/package.json
  samples/quickstart.js
  samples/test/quickstart.test.js
  synth.metadata
Labels: api: cloudfunctions, cla: yes, samples
